#############################################
#                                           #
#      This is the Configuration file       #
#        for the LandClaimX plugin          #
#                                           #
#############################################

#General settings
Plugin:
  #Should the plugin print all lines of claims.yml to the console when it gets enabled
  #Change to "false" to disable
  #Default: "true"
  doclaimsreadprint: true
  #The world that the plugin allows the '/claim' command to be used
  worldname: "world"