name: Landclaimx
version: '${project.version}'
main: com.x_tornado10.landclaimx.LandClaimX
api-version: 1.19
commands:
  claim:
    description: Lets sender claim current chunk.
    usage:
    aliases: cl
    permission: landclaimx.claim
    permission-message: You do not have permission to execute that command!